// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Soube.Infrastructure.ADO.Data;

public partial class Aluno
{
    [Key]
    public int Id { get; set; }

    public int Score { get; set; }

    public int QuestoesRealizadas { get; set; }

    public int QuestoesAcertadas { get; set; }

    public int PessoaFisicaId { get; set; }

    [ForeignKey("PessoaFisicaId")]
    [InverseProperty("Aluno")]
    public virtual PessoaFisica PessoaFisica { get; set; }

    [InverseProperty("Aluno")]
    public virtual ICollection<SimuladoQuestao> SimuladoQuestao { get; } = new List<SimuladoQuestao>();
}