// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Soube.Infrastructure.ADO.Data;

public partial class Autenticar
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Login { get; set; }

    [Required]
    [StringLength(16)]
    [Unicode(false)]
    public string Senha { get; set; }

    [InverseProperty("Autenticar")]
    public virtual ICollection<Pessoa> Pessoa { get; } = new List<Pessoa>();
}