// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Soube.Infrastructure.ADO.Data;

public partial class Materia
{
    [Key]
    public int Id { get; set; }

    [StringLength(40)]
    [Unicode(false)]
    public string Nome { get; set; }

    [StringLength(800)]
    [Unicode(false)]
    public string ImagemURL { get; set; }

    public int? Escolaridade { get; set; }

    public int? Nivel { get; set; }

    public int SituacaoId { get; set; }

    [InverseProperty("Materia")]
    public virtual ICollection<Questao> Questao { get; } = new List<Questao>();

    [ForeignKey("SituacaoId")]
    [InverseProperty("Materia")]
    public virtual Situacao Situacao { get; set; }
}