// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Soube.Infrastructure.ADO.Data;

public partial class PessoaFisica
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(11)]
    [Unicode(false)]
    public string CPF { get; set; }

    [Required]
    [StringLength(13)]
    [Unicode(false)]
    public string RG { get; set; }

    [Required]
    [StringLength(8)]
    [Unicode(false)]
    public string Passaporte { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nacionalidade { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Naturalidade { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string EstadoCivil { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string Sexo { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Genero { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataNascimento { get; set; }

    public int PessoaId { get; set; }

    [InverseProperty("PessoaFisica")]
    public virtual ICollection<Aluno> Aluno { get; } = new List<Aluno>();

    [ForeignKey("PessoaId")]
    [InverseProperty("PessoaFisica")]
    public virtual Pessoa Pessoa { get; set; }

    [InverseProperty("Administrador")]
    public virtual ICollection<Situacao> Situacao { get; } = new List<Situacao>();
}