// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Soube.Infrastructure.ADO.Data;

public partial class Pessoa
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Nome { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Telefone { get; set; }

    [StringLength(13)]
    [Unicode(false)]
    public string Celular { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    public int Credencial { get; set; }

    public int EnderecoId { get; set; }

    public int SituacaoId { get; set; }

    public int AutenticarId { get; set; }

    [ForeignKey("AutenticarId")]
    [InverseProperty("Pessoa")]
    public virtual Autenticar Autenticar { get; set; }

    [ForeignKey("EnderecoId")]
    [InverseProperty("Pessoa")]
    public virtual Endereco Endereco { get; set; }

    [InverseProperty("Pessoa")]
    public virtual ICollection<PessoaFisica> PessoaFisica { get; } = new List<PessoaFisica>();

    [InverseProperty("Pessoa")]
    public virtual ICollection<PessoaJuridica> PessoaJuridica { get; } = new List<PessoaJuridica>();

    [ForeignKey("SituacaoId")]
    [InverseProperty("Pessoa")]
    public virtual Situacao Situacao { get; set; }
}