// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Soube.Infrastructure.ADO.Data;

public partial class PessoaJuridica
{
    [Key]
    public int Id { get; set; }

    [StringLength(14)]
    [Unicode(false)]
    public string CNPJ { get; set; }

    [StringLength(80)]
    [Unicode(false)]
    public string Fantasia { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string RazaoSocial { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataInicioAtividade { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string DescricaoSituacaoCadastral { get; set; }

    public bool? Matriz { get; set; }

    public int PessoaId { get; set; }

    [ForeignKey("PessoaId")]
    [InverseProperty("PessoaJuridica")]
    public virtual Pessoa Pessoa { get; set; }

    [InverseProperty("Banca")]
    public virtual ICollection<Questao> Questao { get; } = new List<Questao>();
}