// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Soube.Infrastructure.ADO.Data;

public partial class Simulado
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataCriacao { get; set; }

    public int? TempoMaximo { get; set; }

    public int? NumQuestoes { get; set; }

    public int? NotaMaxima { get; set; }

    public int? NotaObtida { get; set; }

    [InverseProperty("Simulado")]
    public virtual ICollection<Questao> Questao { get; } = new List<Questao>();

    [InverseProperty("Simulado")]
    public virtual ICollection<SimuladoQuestao> SimuladoQuestao { get; } = new List<SimuladoQuestao>();
}