// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Soube.Infrastructure.ADO.Data;

public partial class SimuladoQuestao
{
    [Key]
    public int Id { get; set; }

    public int? SimuladoId { get; set; }

    public int? QuestaoId { get; set; }

    public int? AlunoId { get; set; }

    [ForeignKey("AlunoId")]
    [InverseProperty("SimuladoQuestao")]
    public virtual Aluno Aluno { get; set; }

    [ForeignKey("QuestaoId")]
    [InverseProperty("SimuladoQuestao")]
    public virtual Questao Questao { get; set; }

    [ForeignKey("SimuladoId")]
    [InverseProperty("SimuladoQuestao")]
    public virtual Simulado Simulado { get; set; }
}