// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Soube.Infrastructure.ADO.Data;

public partial class Situacao
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Criado { get; set; }

    public int CriadoPor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Atualizado { get; set; }

    public int AtualizadoPor { get; set; }

    [Required]
    public bool? Ativo { get; set; }

    public int AdministradorId { get; set; }

    [ForeignKey("AdministradorId")]
    [InverseProperty("Situacao")]
    public virtual PessoaFisica Administrador { get; set; }

    [InverseProperty("Situacao")]
    public virtual ICollection<Materia> Materia { get; } = new List<Materia>();

    [InverseProperty("Situacao")]
    public virtual ICollection<Pessoa> Pessoa { get; } = new List<Pessoa>();

    [InverseProperty("Situacao")]
    public virtual ICollection<Questao> Questao { get; } = new List<Questao>();
}